<?php

namespace CidadesBundle\Repository;

/**
 * CidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
