<?php

namespace CidadesBundle\Repository;

/**
 * RegioesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegioesRepository extends \Doctrine\ORM\EntityRepository
{
}
