<?php

namespace CidadesBundle\Repository;

/**
 * TiposCidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposCidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
