<?php

namespace FornecedoresBundle\Repository;

/**
 * ContatosFornecedoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatosFornecedoresRepository extends \Doctrine\ORM\EntityRepository
{
}
