<?php

namespace FornecedoresBundle\Repository;

/**
 * FornecedoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FornecedoresRepository extends \Doctrine\ORM\EntityRepository
{
}
