<?php

namespace FabricantesBundle\Repository;

/**
 * FabricantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricantesRepository extends \Doctrine\ORM\EntityRepository
{
}
