<?php

namespace MateriaisBundle\Repository;

/**
 * CategoriasMateriaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasMateriaisRepository extends \Doctrine\ORM\EntityRepository
{
}
