<?php

namespace MateriaisBundle\Repository;

/**
 * MateriaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaisRepository extends \Doctrine\ORM\EntityRepository
{
}
