<?php

namespace MateriaisBundle\Repository;

/**
 * TiposMateriaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposMateriaisRepository extends \Doctrine\ORM\EntityRepository
{
}
