<?php

namespace MateriaisBundle\Repository;

/**
 * TiposUnidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposUnidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
